/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidupdate_jni_PatchUtil */

#ifndef _Included_com_droidupdate_jni_PatchUtil
#define _Included_com_droidupdate_jni_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidupdate_jni_PatchUtil
 * Method:    applyPatchToOldApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_droidupdate_jni_PatchUtil_applyPatchToOldApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
